name: adaptive-ensemble
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - pytorch-cpu        # نسخهٔ CPU‑Only از PyTorch
  - joblib
  - pytest
  - sphinx
  - mkdocs