name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug: show working dir and files
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          echo "Contents of workspace:"
          ls -R $GITHUB_WORKSPACE

      - name: Install dependencies
        working-directory: ${{ github.workspace }}/Adaptive-Cantext-Aware-Ensemble
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e . pytest

      - name: Run tests
        working-directory: ${{ github.workspace }}/Adaptive-Cantext-Aware-Ensemble
        run: python -m pytest --maxfail=1 --disable-warnings -q